version: "3.8"
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: SOMERESTSERVER
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
